// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: words-queries.sql

package storage

import (
	"context"
)

const getWords = `-- name: GetWords :many
SELECT word
FROM words
`

func (q *Queries) GetWords(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getWords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var word string
		if err := rows.Scan(&word); err != nil {
			return nil, err
		}
		items = append(items, word)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveWord = `-- name: SaveWord :exec
INSERT INTO words (word)
VALUES(?)
`

func (q *Queries) SaveWord(ctx context.Context, word string) error {
	_, err := q.db.ExecContext(ctx, saveWord, word)
	return err
}
