// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: subjects-queries.sql

package subjectsdb

import (
	"context"
)

const getSubjects = `-- name: GetSubjects :many
SELECT (subject, words)
FROM subjects
`

func (q *Queries) GetSubjects(ctx context.Context) ([]interface{}, error) {
	rows, err := q.db.QueryContext(ctx, getSubjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []interface{}
	for rows.Next() {
		var column_1 interface{}
		if err := rows.Scan(&column_1); err != nil {
			return nil, err
		}
		items = append(items, column_1)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveSubject = `-- name: SaveSubject :exec
INSERT INTO subjects(subject, words)
VALUES (?, ?)
`

type SaveSubjectParams struct {
	Subject string
	Words   string
}

func (q *Queries) SaveSubject(ctx context.Context, arg SaveSubjectParams) error {
	_, err := q.db.ExecContext(ctx, saveSubject, arg.Subject, arg.Words)
	return err
}
