// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
)

type Apikey struct {
	Key  string
	Name string
	Uid  sql.NullInt64
}

type Board struct {
	ID       int64
	Subject1 sql.NullInt64
	Subject2 sql.NullInt64
	Subject3 sql.NullInt64
	Subject4 sql.NullInt64
	Played   sql.NullInt64
	Wins     sql.NullInt64
}

type Game struct {
	ID     int64
	Active sql.NullBool
	Turns  sql.NullInt64
	Wrong  sql.NullInt64
	Win    sql.NullBool
	Start  sql.NullInt64
	End    sql.NullInt64
	Bid    sql.NullInt64
}

type Session struct {
	Accesstoken  string
	Refreshtoken string
	Valid        sql.NullInt64
}

type Subject struct {
	ID    int64
	Name  string
	Word1 int64
	Word2 int64
	Word3 int64
	Word4 int64
}

type User struct {
	ID        int64
	Username  string
	Password  string
	Email     string
	Reset     sql.NullString
	ResetTime sql.NullInt64
}

type UsersGame struct {
	Uid int64
	Gid int64
}

type Word struct {
	ID    int64
	Value string
	Word  string
}
