version: "3.7"

services:
  app:
    image: ghcr.io/cg219/common-game:main
    environment:
      - APP_DATA=data/database.db
      - APP_CREDENTIALS=/run/secrets/cgsecrets
      - APP_EXIT_BACKUP=1
      - PORT=8080
    ports:
      - 3007:8080
    volumes:
      - thecommongame-data:/app/data
    secrets:
      - cgsecrets
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/healthcheck"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
    deploy:
      restart_policy:
        condition: on-failure
  backup:
    image: ghcr.io/cg219/common-game:main
    environment:
      - APP_DATA=data/database.db
      - APP_CREDENTIALS=/run/secrets/cgsecrets
      - APP_EXIT_BACKUP=1
      - PORT=8081
    command: ["/bin/sh", "-c", "while ! wget --spider -q http://thecommongame_app:8080/health; do sleep 10; done; /app/backup"]
    volumes:
      - thecommongame-data:/app/data
    secrets:
      - cgsecrets
    deploy:
      restart_policy:
        condition: on-failure

secrets:
  cgsecrets:
    file: secrets.yaml

volumes:
  thecommongame-data:
