version: "3.7"

services:
  app:
    image: ghcr.io/cg219/common-game:main
    environment:
      - APP_DATA=data/database.db
      - APP=/run/secrets/npsecrets
      - PORT=8080
    ports:
      - 3007:8080
    volumes:
      - thecommongame-data:/app/data
    secrets:
      - npsecrets
  backup:
    image: ghcr.io/cg219/common-game:main
    environment:
      - APP_DATA=data/database.db
      - NP_CREDTENTIALS=/run/secrets/npsecrets
      - APP_EXIT_BACKUP=1
      - PORT=8081
    command: ["/bin/sh", "-c", "while ! wget --spider -q http://thecommongame_app:8080/health; do sleep 2; done; /app/backup"]
    volumes:
      - thecommongame-data:/app/data
    secrets:
      - npsecrets
    deploy:
      restart_policy:
        condition: on-failure

secrets:
  npsecrets:
    file: secrets.yaml

volumes:
  thecommongame-data:

