// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package data

import (
	"database/sql"
)

type Game struct {
	ID       int64
	Active   sql.NullBool
	Turns    sql.NullInt64
	Wrong    sql.NullInt64
	Win      sql.NullBool
	Start    sql.NullInt64
	End      sql.NullInt64
	PlayerID sql.NullInt64
}

type Player struct {
	ID   int64
	Name sql.NullString
}

type Subject struct {
	ID      int64
	Subject string
	Words   string
	Used    sql.NullInt64
	Correct sql.NullInt64
}

type Word struct {
	ID   int64
	Word string
}
