// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package data

import (
	"context"
)

const getSubjects = `-- name: GetSubjects :many
SELECT subject, words FROM subjects
`

type GetSubjectsRow struct {
	Subject string
	Words   string
}

func (q *Queries) GetSubjects(ctx context.Context) ([]GetSubjectsRow, error) {
	rows, err := q.db.QueryContext(ctx, getSubjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSubjectsRow
	for rows.Next() {
		var i GetSubjectsRow
		if err := rows.Scan(&i.Subject, &i.Words); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubjectsForGame = `-- name: GetSubjectsForGame :many
WITH randomrows AS (
    SELECT id, subject, words
    FROM subjects
    ORDER BY random()
    LIMIT 4
),
single_words AS (
    SELECT randomrows.id, json_extract(json_each.value) AS stringv
    FROM randomrows, json_each(randomrows.words)
)
SELECT id, subject, words
FROM randomrows
WHERE NOT EXISTS (
    SELECT 1
    FROM single_words l1
    JOIN single_words l2 ON l1.stringv = l2.stringv AND l1.id != l2.id
    WHERE l1.id = randomrows.id
)
`

type GetSubjectsForGameRow struct {
	ID      int64
	Subject string
	Words   string
}

func (q *Queries) GetSubjectsForGame(ctx context.Context) ([]GetSubjectsForGameRow, error) {
	rows, err := q.db.QueryContext(ctx, getSubjectsForGame)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSubjectsForGameRow
	for rows.Next() {
		var i GetSubjectsForGameRow
		if err := rows.Scan(&i.ID, &i.Subject, &i.Words); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWords = `-- name: GetWords :many
SELECT word
FROM words
`

func (q *Queries) GetWords(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getWords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var word string
		if err := rows.Scan(&word); err != nil {
			return nil, err
		}
		items = append(items, word)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveSubject = `-- name: SaveSubject :exec
INSERT INTO subjects(subject, words)
VALUES (?, ?)
`

type SaveSubjectParams struct {
	Subject string
	Words   string
}

func (q *Queries) SaveSubject(ctx context.Context, arg SaveSubjectParams) error {
	_, err := q.db.ExecContext(ctx, saveSubject, arg.Subject, arg.Words)
	return err
}

const saveWord = `-- name: SaveWord :exec
INSERT INTO words (word)
VALUES(?)
`

func (q *Queries) SaveWord(ctx context.Context, word string) error {
	_, err := q.db.ExecContext(ctx, saveWord, word)
	return err
}
