CREATE TABLE IF NOT EXISTS words (
    id INTEGER PRIMARY KEY,
    word TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS subjects (
    id INTEGER PRIMARY KEY,
    subject TEXT NOT NULL,
    words TEXT NOT NULL,
    used INTEGER DEFAULT 0,
    correct INTEGER DEFAULT 0
);
